import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'
import { useSession, signIn, signOut,getSession } from 'next-auth/react';

export default function Home({user}) {
  return (
    <>
      <Head>
        <title>Quitutes de Venus | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
        <Hero/>
    </main>
    </>
  )
}

