import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Quitutes de Venus | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
        <Hero/>
    </main>
    </>
  )
}

export const getServerSideProps : GetServerSideProps = async ()=>{
  const res = await fetch("https://fakestoreapi.com/products?limit=5")
  const data = await res.json()
  return { 
    props:{
      data
    }
  }
}